"""initial production schema

Revision ID: a946c6d10b59
Revises:
Create Date: 2026-07-26 14:57:34.813079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a946c6d10b59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'subject', name='uq_users_tenant_subject')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('active_index_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_knowledge_bases_tenant_name')
    )
    op.create_index(op.f('ix_knowledge_bases_tenant_id'), 'knowledge_bases', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_memberships_tenant_user')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_tenant_updated', 'conversations', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'name', name='uq_folders_kb_name')
    )
    op.create_index('ix_folders_tenant_kb', 'folders', ['tenant_id', 'knowledge_base_id'], unique=False)
    op.create_table('index_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('reranker_model', sa.String(length=255), nullable=False),
    sa.Column('chunk_schema_version', sa.String(length=100), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=255), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('building', 'validating', 'ready', 'active', 'failed', 'retired')", name='ck_index_versions_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'version_number', name='uq_index_versions_kb_number')
    )
    op.create_index('ix_index_versions_tenant_kb_status', 'index_versions', ['tenant_id', 'knowledge_base_id', 'status'], unique=False)
    with op.batch_alter_table('knowledge_bases') as batch_op:
        batch_op.create_foreign_key(
            'fk_knowledge_bases_active_index_version',
            'index_versions',
            ['active_index_version_id'],
            ['id'],
            ondelete='SET NULL',
        )
    op.create_table('answer_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('pipeline_version', sa.String(length=100), nullable=False),
    sa.Column('index_version_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('retrieval_needed', sa.Boolean(), nullable=False),
    sa.Column('source_ids_json', sa.JSON(), nullable=False),
    sa.Column('timings_json', sa.JSON(), nullable=False),
    sa.Column('retrieval_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answer_runs_tenant_created', 'answer_runs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_documents_tenant_source')
    )
    op.create_index('ix_documents_tenant_kb_status', 'documents', ['tenant_id', 'knowledge_base_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_tenant_conversation', 'messages', ['tenant_id', 'conversation_id', 'created_at'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('extracted_object_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('chunk_schema_version', sa.String(length=100), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_number')
    )
    op.create_index('ix_document_versions_tenant_document', 'document_versions', ['tenant_id', 'document_id'], unique=False)
    with op.batch_alter_table('documents') as batch_op:
        batch_op.create_foreign_key(
            'fk_documents_current_version',
            'document_versions',
            ['current_version_id'],
            ['id'],
            ondelete='SET NULL',
        )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('answer_run_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating IN (-1, 0, 1)', name='ck_feedback_rating'),
    sa.ForeignKeyConstraint(['answer_run_id'], ['answer_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'answer_run_id', name='uq_feedback_user_run')
    )
    op.create_index('ix_feedback_tenant_created', 'feedback', ['tenant_id', 'created_at'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('index_version_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_key', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_version_id', 'chunk_key', name='uq_chunks_index_chunk_key')
    )
    op.create_index('ix_chunks_tenant_document_version', 'chunks', ['tenant_id', 'document_version_id'], unique=False)
    op.create_index('ix_chunks_tenant_kb_index', 'chunks', ['tenant_id', 'knowledge_base_id', 'index_version_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('worker_task_id', sa.String(length=255), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_tenant_status', 'ingestion_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('answer_run_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_record_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_run_id'], ['answer_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_record_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citations_tenant_run', 'citations', ['tenant_id', 'answer_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citations_tenant_run', table_name='citations')
    op.drop_table('citations')
    op.drop_index('ix_ingestion_jobs_tenant_status', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_chunks_tenant_kb_index', table_name='chunks')
    op.drop_index('ix_chunks_tenant_document_version', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_feedback_tenant_created', table_name='feedback')
    op.drop_table('feedback')
    with op.batch_alter_table('documents') as batch_op:
        batch_op.drop_constraint('fk_documents_current_version', type_='foreignkey')
    op.drop_index('ix_document_versions_tenant_document', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_messages_tenant_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_documents_tenant_kb_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_answer_runs_tenant_created', table_name='answer_runs')
    op.drop_table('answer_runs')
    with op.batch_alter_table('knowledge_bases') as batch_op:
        batch_op.drop_constraint(
            'fk_knowledge_bases_active_index_version',
            type_='foreignkey',
        )
    op.drop_index('ix_index_versions_tenant_kb_status', table_name='index_versions')
    op.drop_table('index_versions')
    op.drop_index('ix_folders_tenant_kb', table_name='folders')
    op.drop_table('folders')
    op.drop_index('ix_conversations_tenant_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_knowledge_bases_tenant_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_audit_events_tenant_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('tenants')
    # ### end Alembic commands ###
